#!/bin/bash

# start daemons
sxhkd & 
dunst &
warpd &

# set wallpaper
feh --bg-fill --no-fehbg ~/.config/wallpapers/chosen/48\ -\ blu│ 10 #!/bin/bash
e\ sky\ whale.jpg

# create desktops a, s, d, f, u, i, o, p
bspc monitor -d a s d f u i o p

# add gaps
bspc config window_gap 20

# selected node border width
bspc config border_width 2
